openapi: 3.0.0
info:
  description: This API provides event stats
  version: "1.0.0"
  title: Stats API
  contact:
    email: hkim444@my.bcit.ca

paths:
  /health:
    get:
      tags:
        - devices
      summary: Returns status of the service
      description: Returns the health status of the service
      operationId: app.get_health_status
      responses:
        '200':
          description: Service is running
        '500':
          description: Service is down
  /stats:
    get:
      summary: Gets the event stats
      operationId: app.get_stats
      description: Gets book holds and movie holds processsed statistics
      responses:
        '200':
          description: Successfully returned a list of hold requests
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ReadingStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string


components:
  schemas:
    ReadingStats:
      required:
      - num_bh_requests
      - num_mh_requests
      - max_bh_availability
      - max_mh_availability
      properties:
        num_bh_requests:
          type: integer
          example: 500000
        num_mh_requests:
          type: integer
          example: 10
        num_bh_availability:
          type: integer
          example: 2
        num_mh_availability:
          type: integer
          example: 500000
      type: object